### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by yang-yi-li** [Bingjian-Zhu/gin-vue-admin#1]
2019/12/12 16:01:37 [Setting] config error:  open ../Config/config.yml: The system cannot find the path specified.
2019/12/12 16:01:37 [Setting] Config init success
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa70dcf]

**Comment by Bingjian-Zhu** [comment]
@yang-yi-li 把Go Modules设置成on或者auto试试
