### ISSUE TITLE
前后端使用同一个端口可以嘛

### ISSUE THREAD

**Issue by kxjhcs** [Bingjian-Zhu/gin-vue-admin#5]
请问一下，如何实现前后端使用同一个端口呢

**Comment by Bingjian-Zhu** [comment]
@kxjhcs 思路：把Vue程序编译后的静态文件放到Go程序下，然后当静态文件访问。需要注意的是，Vue程序需要配置后台API接口的地址

**Comment by kxjhcs** [comment]
谢谢，用github.com/gin-contrib/static 解决了
