### ISSUE TITLE
当我登录成功后，修改jwt-token的值，前端会无限次调用 /refresh_token ！

### ISSUE THREAD

**Issue by Carrotxyy** [Bingjian-Zhu/gin-vue-admin#6]
在我修改了cookie jwt-token后，发起一个正常的请求，这时服务器发现这不是一个合法的token，
回调了Unauthorized: func(c *gin.Context, code int, message string)
并且code = 401
这个时候前端响应拦截器发现请求失败401，获取cookie中token-expire的值比对token是否过期，
发现未过期，就会发起 /refresh_token 请求
这个时候发现，由于token还是非法，服务器又会返回401，
前端接收响应，请求失败401，又判断token是否过期，这就会无限循环下去！直到服务器崩了，或者token过期

因为当jwt错误，Unauthorized回调参数code都为401，难道只能根据message不同来判断吗？这样好吗

**请问该如何处理这个问题，谢谢**

**Comment by Bingjian-Zhu** [comment]
@Carrotxyy 
默认的`RefreshResponse`函数
```go
		RefreshResponse: func(c *gin.Context, code int, token string, t time.Time) {
			cookie, err := c.Cookie("jwt")
			if err != nil {
				log.Println(err)
			}

			c.JSON(http.StatusOK, gin.H{
				"code":    http.StatusOK,
				"token":   token,
				"expire":  t.Format(time.RFC3339),
				"message": "refresh successfully",
				"cookie":  cookie,
			})
		},
```
这是因为`/refresh_token`执行的只是更新`token`过期时间导致的，你可以在`gin-vue-admin/common/middleware/jwt/jwt.go`文件中，重写`RefreshResponse`函数，每次`/refresh_token`，就重新生成一个token

**Comment by Carrotxyy** [comment]
@Bingjian-Zhu 
还是会出现问题！
因为jwt在解析token的时候就会发生错误，直接回调Unauthorized，
RefreshResponse 无法被执行
```
func (mw *GinJWTMiddleware) RefreshHandler(c *gin.Context) {
	tokenString, expire, err := mw.RefreshToken(c)   // 这里解析token，发生错误
	if err != nil {
		mw.unauthorized(c, http.StatusUnauthorized, mw.HTTPStatusMessageFunc(err, c))
		return
	}

	mw.RefreshResponse(c, http.StatusOK, tokenString, expire)
}

```

主要问题是，jwt发生任何错误调用Unauthorized，错误码都是401，这样就无法辨别错误类型，从而进行不同的操作

我看见您在前端 ./vue-admin/src/utils/request.js 拦截器中，有一段代码
`


      // 50008: Illegal token; 50012: Other clients logged in; 50014: Token expired;
      if (res.code === 50008 || res.code === 50012 || res.code === 50014) {
        // to re-login
        MessageBox.confirm('You have been logged out, you can cancel to stay on this page, or log in again', 'Confirm logout', {
          confirmButtonText: 'Re-Login',
          cancelButtonText: 'Cancel',
          type: 'warning'
        }).then(() => {
          store.dispatch('user/resetToken').then(() => {
            location.reload()
          })
        })
      }
`
我发现后端响应没有定义这些错误码，
并且后端是如何判断token的状态是非法 (Illegal token)

因为我测试时，人为修改了token,造成token是非法的，
但是运用 userAPI.Use(authMiddleware.MiddlewareFunc()) 中间件，无法根据回调Unauthorized 中的错误码判断错误类型，从而执行不同操作

**麻烦您能指点指点**

**Comment by Bingjian-Zhu** [comment]
@Carrotxyy 这些代码是`http://panjiachen.github.io/vue-admin-template`模板原有，这里没有用到，可以删掉
```js
func (mw *GinJWTMiddleware) RefreshHandler(c *gin.Context) {
	tokenString, expire, err := mw.RefreshToken(c)   // 这里解析token，发生错误
	if err != nil {
		mw.unauthorized(c, http.StatusUnauthorized, mw.HTTPStatusMessageFunc(err, c))
		return
	}

	mw.RefreshResponse(c, http.StatusOK, tokenString, expire)
}
```

```
tokenString, expire, err := mw.RefreshToken(c)   // 这里解析token，发生错误
```
你既然知道解析token时候发生错误，不能刷新token，那你就看他怎样解析token的啊，继续翻他的源码，相信你会找到解决方案的，不要害怕看源码

**Comment by Carrotxyy** [comment]
@Bingjian-Zhu 
谢谢您的指点
